@description('Validated Azure region for all resources.')
param location string = resourceGroup().location

@description('Short environment name for deterministic resource names.')
param environmentName string = 'demo'

@description('Bootstrap image replaced by the deployment script after ACR creation.')
param bootstrapImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Region for Foundry and AI Search after availability validation.')
param foundryLocation string = 'japaneast'

@description('Small Linux worker VM SKU.')
param vmSize string = 'Standard_B2s'

@description('SSH public key generated by the deployment script.')
param adminSshPublicKey string

@description('Include cloud-init when creating a new worker VM. Disable when updating an existing VM.')
param configureWorkerBootstrap bool = true

var token = uniqueString(subscription().id, resourceGroup().id, location, environmentName)
var acrPullRoleId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d')
var tags = { application: 'eda-iq-demo', environment: environmentName, dataClass: 'synthetic-only' }

resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' = {
  name: 'azid${token}'
  location: location
  tags: tags
}

resource registry 'Microsoft.ContainerRegistry/registries@2025-04-01' = {
  name: 'azacr${token}'
  location: location
  tags: tags
  sku: { name: 'Basic' }
  properties: {
    adminUserEnabled: false
    anonymousPullEnabled: false
    publicNetworkAccess: 'Enabled'
  }
}

resource registryPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(registry.id, identity.id, acrPullRoleId)
  scope: registry
  properties: {
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: acrPullRoleId
  }
}

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: 'azlog${token}'
  location: location
  tags: tags
  properties: {
    features: { enableLogAccessUsingOnlyResourcePermissions: true }
    retentionInDays: 30
    sku: { name: 'PerGB2018' }
  }
}

resource insights 'Microsoft.Insights/components@2020-02-02' = {
  name: 'azai${token}'
  location: location
  kind: 'web'
  tags: tags
  properties: {
    Application_Type: 'web'
    DisableLocalAuth: true
    IngestionMode: 'LogAnalytics'
    WorkspaceResourceId: logAnalytics.id
  }
}

module storageCompute 'storage-compute.bicep' = {
  name: 'azmodsc${token}'
  params: {
    adminSshPublicKey: adminSshPublicKey
    appIdentityPrincipalId: identity.properties.principalId
    configureWorkerBootstrap: configureWorkerBootstrap
    location: location
    resourceToken: token
    tags: tags
    vmSize: vmSize
  }
}

module foundryStack 'foundry.bicep' = {
  name: 'azmodai${token}'
  params: {
    appIdentityPrincipalId: identity.properties.principalId
    location: foundryLocation
    resourceToken: token
    tags: tags
  }
}

resource environment 'Microsoft.App/managedEnvironments@2025-01-01' = {
  name: 'azcae${token}'
  location: location
  tags: tags
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
    vnetConfiguration: {
      infrastructureSubnetId: storageCompute.outputs.containerAppsSubnetId
      internal: false
    }
    workloadProfiles: [{
      name: 'Consumption'
      workloadProfileType: 'Consumption'
    }]
    zoneRedundant: false
  }
}

resource app 'Microsoft.App/containerApps@2025-01-01' = {
  name: 'azca${token}'
  location: location
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  properties: {
    environmentId: environment.id
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        allowInsecure: false
        corsPolicy: {
          allowedHeaders: ['content-type', 'mcp-protocol-version']
          allowedMethods: ['GET', 'POST', 'DELETE']
          allowedOrigins: ['*']
        }
        external: true
        targetPort: 3000
        traffic: [{ latestRevision: true, weight: 100 }]
        transport: 'auto'
      }
      registries: [{ identity: identity.id, server: registry.properties.loginServer }]
    }
    template: {
      containers: [{
        name: 'eda-iq-demo'
        image: bootstrapImage
        env: [
          { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: insights.properties.ConnectionString }
          { name: 'DEMO_DATA_CLASS', value: 'synthetic-only' }
          { name: 'AZURE_CLIENT_ID', value: identity.properties.clientId }
          { name: 'AZURE_STORAGE_ACCOUNT_NAME', value: storageCompute.outputs.storageAccountName }
          { name: 'OPC_QUEUE_NAME', value: storageCompute.outputs.queueName }
          { name: 'OPC_RESULTS_CONTAINER', value: storageCompute.outputs.resultContainerName }
          { name: 'AZURE_AI_PROJECT_ENDPOINT', value: foundryStack.outputs.foundryProjectEndpoint }
          { name: 'AZURE_AI_SEARCH_NAME', value: foundryStack.outputs.searchServiceName }
        ]
        resources: { cpu: json('0.5'), memory: '1Gi' }
      }]
      scale: { minReplicas: 1, maxReplicas: 1 }
    }
  }
  dependsOn: [registryPull]
}

output deployment object = {
  applicationUrl: 'https://${app.properties.configuration.ingress.fqdn}'
  mcpEndpoint: 'https://${app.properties.configuration.ingress.fqdn}/api/mcp'
  containerAppName: app.name
  registryName: registry.name
  registryLoginServer: registry.properties.loginServer
  storageAccountName: storageCompute.outputs.storageAccountName
  workerVmName: storageCompute.outputs.vmName
  foundryAccountName: foundryStack.outputs.foundryAccountName
  foundryProjectName: foundryStack.outputs.foundryProjectName
  foundryProjectEndpoint: foundryStack.outputs.foundryProjectEndpoint
  searchServiceName: foundryStack.outputs.searchServiceName
}
